### ISSUE TITLE
fpylll : doesn't work in Windows, only in Linux.

### ISSUE THREAD

**Issue by ramin1234** [bitlogik/lattice-attack#11]
hi
how can i use your program in windows ?
is there any solution?

**Comment by bitlogik** [comment]
LatticeAttack depends on fpylll which depends on fplll, which only works on Unix like systems, because it uses many GNU libraries for the underlying computation.

I think of 2 ways to work this around : 
- Use WSL, so you run a Linux system in your Windows. You may have the pip package _python3-fpylll_ available to install. Also you can e[ven compile the fplll in](https://github.com/fplll/fplll#windows-10) this WSL (not easy).
- Use an [web online service](https://github.com/fplll/fpylll#online) which provides a Python interpreter online, such as Sage, CoCalc or Jupyter notebook. Or alternatively, a [virtual Linux machine remote](https://www.onworks.net/os-distributions/ubuntu-based/free-ubuntu-online-version-20) or a Linux console in a web page.
