### ISSUE TITLE
How many set of signatures needed? 

### ISSUE THREAD

**Issue by KrashKrash** [bitlogik/lattice-attack#17]
Hi. I had run the lattice attack on a wallet but it says, "private key not found. Sorry for your loss."

I'm just wondering, to recover a wallet private key, how many set of signatures Are needed? I had entered 50 set of signatures.

Was it enough?

**Comment by bitlogik** [comment]
That means the private key was not recovered, probably because of bad data. The LatticeAttack software checks if the number of signatures is enough in order to be able to recover. If it doesn't say "Not enough signatures", that means it estimates there is enough signatures number to be able to recover the private key.
Basically, you just need "a little over" the sum of know bits. For example, for an ECDSA 256 bits key, if you know 8 bits of the secret nonce per signature, you need more than 32 signatures. In practice (computed by LatticeAttack as the limit), that would be something like >=44. This is a kind of magical part in LatticeAttack (HNP, SVP solved), that the known bits are added up to the private key length. [See there for more details](https://github.com/bitlogik/lattice-attack/issues/9#issuecomment-970256094) about the underlying math theory. Of course that depends of the key size, and the known bits per signature. But LatticeAttack takes this as input, and computes a correct estimation of the number needed, and displays an error if too few signatures (which stops the software, and it doesn't perform the recovery).
Note that the HNP/SVP technique is very very sensible to bad data. We can view this as an exact method, and a single false bit in the matrix makes it not working. This is not a heuristic method. What "saves" you is that the LatticeAttack select a sub-number of signatures inside the data you provide (to minimize the matrix size, hence the time it takes), and you can use the loop mode, with "-l" arg. So each try it randomly select a subset of your signatures. But you need a very low level or error (just a few bad signatures/nonce data), else the probability of having bad data in the matrix is very high.
