### ISSUE TITLE
Does your script work with 9 bits of k (LSB) and above?

### ISSUE THREAD

**Issue by amiwrcd** [bitlogik/lattice-attack#6]
Hello BitLogiK! Thank you for providing an example from the research paper:  dataset ["ECDummyRPA"](https://github.com/bitlogik/lattice-attack/blob/master/Data/ECDummyRPA/gen_input.py)

But I have a question here

I run [lattice_attack.py](https://github.com/bitlogik/lattice-attack/blob/master/lattice_attack.py) with `"known_bits": 7`
with known bits:
`0b0000000 -> "kp": 0`

Running with 7 bits of k (LSB)

Then, having received the private key, I checked which "Nonce k" gave us a successful result.

After digging around, I found out that these two values "Nonce k" contain the same bits `"b180"` at the end

```
0x995db4b69ed0e9ab0f1504b04d6d7d6b427d68280f28b5780bd7aa02a010b180
0x4fc8123eafc50f38f58a741b55b324c46b6f820ebe70b4330f55b173d76cb180
```

In _binary format_, they end with` 0000000`

```
1001100101011101101101001011011010011110110100001110100110101011000011110001010100000100101100000100110101101101011111010110101101000010011111010110100000101000000011110010100010110101011110000000101111010111101010100000001010100000000100001011000110000000
0100111111001000000100100011111010101111110001010000111100111000111101011000101001110100000110110101010110110011001001001100010001101011011011111000001000001110101111100111000010110100001100110000111101010101101100010111001111010111011011001011000110000000
```

But I decided to look at other "Nonce k" as well. It turned out that there is a "Nonce k" which ends in 9 bits of k (LSB)

For example, these values contain the same bits `"0200"`:

```
0xb534bc4b3274e0e296ac90e925dbff02e8f283ac2c8af87360949e7d6b4a0200
0xb186ddc3c61cadefd2bf22df4e66a4aa9175cff861a57d9487150707c4c10200
```

In _binary format_, they end with `000000000`
That is, they contain 9 trailing zeros (LSB)

```
1011010100110100101111000100101100110010011101001110000011100010100101101010110010010000111010010010010111011011111111110000001011101000111100101000001110101100001011001000101011111000011100110110000010010100100111100111110101101011010010100000001000000000
1011000110000110110111011100001111000110000111001010110111101111110100101011111100100010110111110100111001100110101001001010101010010001011101011100111111111000011000011010010101111101100101001000011100010101000001110000011111000100110000010000001000000000
```

I decided to change **"data.json**"  [from [ECDummyRPA](https://github.com/bitlogik/lattice-attack/blob/master/Data/ECDummyRPA/gen_input.py)] and put "known_bits": 9 and run[ lattice_attack.py](https://github.com/bitlogik/lattice-attack/blob/master/Data/ECDummyRPA/gen_input.py), but as a result I didn't get the private key.

`{"curve": "SECP256R1", "public_key": [19855744501372242031577085240121890821626888576883044100849092130874048672183, 24919147442978007553383210636662817177773368570673176473451828585949128949805], "known_type": "LSB", "known_bits": 9, "signatures": [{"hash": 27363340138037516625856982544289008292099343323959365703837992137627472480526, "r": 6817743984443539774052 ................... etc.`

```
 ----- Lattice ECDSA Attack ----- 
Loading data from file data.json
Running with 9 bits of k (LSB)
Starting recovery attack (curve SECP256R1)
Constructing matrix
Solving matrix ...
LLL reduction
BKZ reduction : block size = 15
BKZ reduction : block size = 25
BKZ reduction : block size = 40
BKZ reduction : block size = 50
BKZ reduction : block size = 60
Private key not found. Sorry For Your Loss
```

With known bits:
`0b000000000 ... -> "kp": 0`

What is the reason [lattice_attack.py](https://github.com/bitlogik/lattice-attack/blob/master/lattice_attack.py) didn't define these known bits?

Does your [lattice_attack.py](https://github.com/bitlogik/lattice-attack/blob/master/lattice_attack.py) script work with 9 bits of k (LSB) and above?

**Comment by bitlogik** [comment]
It should work with 9 bits, as any other number of known bits higher than 4 bits works (for 256 EC key).

First of all, the condition to find the key is basically the number of known bits should add up to the key length with 4/3. And with a small added margin like 3%, but let's make it simple. To find a 256 bits keys, this requires at least 38 signatures (4/3*256/9). How many keys with the nonce having 9 trailing bits equal to 0 did you use?
As the program makes this computation and test this criteria when you start it, this doesn't seem to be this issue.

More important for your case, if you setup LatticeAttack with kp=0 for all the signatures, with a known bits length of 9, that means all the signatures needs to be as you describe : all the LSB bits must be 0 for all the signatures with kp=0. A signature with kp=0, and  "known_bits" = 9 in the batch settings, means the signature has a nonce ending with 9 bits equals to 0. kp=0 means the nonce ends with 0b000000000.
So did you filter the signatures that only have 9 bits null? Did you configure the kp value to the right value (not 0 when not 9 "0") ? Didn't you mix some signatures with only a smaller "0" and input as "kp=0" ?

I guess that if you only change the "known_bits" value in the batch settings, this can't work because for example at the start the "known_bits" is 7, so it infers with kp=0 that the known nonce ends with 0b0000000. Then with known_bits=9, it infers the known nonce end with 0b000000000. But only some signatures have all the 9 final bits at 0, and many others has a different value. This value should be reflected in "kp".

For example, from one of your nonce : 
...001011000 11 0000000
-> kp = 0  for LSB = 7
-> kp = 384 for LSB = 9

Think of it like a bit mask. So you either compute/provide the right "kp" value. Or you filter/select the transactions that have only 0 for "kp" (all 0). Usually, in practice, the transactions are filtered to only keep the one with 0, because the partial information we get is that it starts or ends with 0, gives a clue. For testing and theory, when you control all the data, you can compute the full kp value which can be different from 0.

We tried with : 
```
python3 gen_data.py -b 9 -n 39 -t LSB
python3 lattice_attack.py
```

And it works flawlessly. The minimum number of signatures accepted is 39 signatures. With lower signatures num, it says there is not enough signatures, which is the first condition, automatically tested. The LatticeAttack script is testing if there is at least this number of signature provided, and if below, it doesn't even try to compute the key.

In case you check twice your data, with the light of these new infos, and you think there is still an issue with the recovery of your dataset, you can send the data to our public email : contact@bitlogik.fr, and we will look deeper at the issue.

**Comment by bitlogik** [comment]
To add some details specific to the dataset in question.
In the code, there is [a comment when it filters the correct signatures](https://github.com/bitlogik/lattice-attack/blob/master/Data/ECDummyRPA/gen_input.py#L122) :
"_A valley considerably lower than the others indicating [a dummy point addition and] a nonce that has its 7 least significant bits set to 0._"
This is a quote [from the original publication](https://www.sstic.org/media/SSTIC2021/SSTIC-actes/return_of_ecc_dummy_point_additions_simple_power_a/SSTIC2021-Article-return_of_ecc_dummy_point_additions_simple_power_analysis_on_efficient_p-256_implementation-russon.pdf), in the §2.3 simulation trace analysis. It states that what we can observe in the "measured" traces are just a discriminatory that indicates if the 7 LSB are all 0.
So, when analyzing the traces, we can only see if the 7 last bits of the nonce are all 0, or different from 0b0000000. So by filtering the traces, you get LSB known_bits=7 with kp=0 (for all relevant traces).
There is no way to get more information, except if you plug back the private key found and compute the nonce for each signatures. But this is a recovery from the private key, hence you go beyond the goal. To work with 9 bits, this would require to filter the signatures that actually have all 9 bits to 0, or alternatively to compute "kp" with the right value as the 2 added bits can be different from 0 if you don't filter. With 2 added bits, if you filter "equal to 0", it means you will keep statistically a quarter of the signatures.

**Comment by amiwrcd** [comment]
@bitlogik  Thank you for such a detailed answer. I truly believe that you will develop this project! I have emailed you.
