### ISSUE TITLE
Hello developer

### ISSUE THREAD

**Issue by heyanheyan** [bitlogik/lattice-attack#7]
Hello developer!
     Can you ask about the article you refer to for constructing matrices? How to attack other known bits? For example, the median is known

**Comment by heyanheyan** [comment]
I find that the construction matrix in your program is different from the references you give

**Comment by bitlogik** [comment]
lattice-attack builds a matrix to solve the Shortest Vector Problem problem of the Hidden Number Problem, with the "recentering" improvement technique. It is very closed from the SVP matrix given in the Minerva reference §4.4 (CVP with added vector). Recentering is described in Minreva §5.3 and §6.4. The basic theory is provided in the master paper from Boneh and Venkatesan. There could be some minor differences because of some practical constraints and optimizations, and also to work with integers so all fractions are multiplied for the bigger denominator (smaller value is 1). But basically there are equivalent from the matrices in the references, because it relies on the exact same theory.

For bits in the middle, not at the end or start, it requires to use the Extended Hidden Number Problem, which is way more complex and with larger matrices. This is described and used in the *Side Journey to Titan* paper. For now LatticeAttack is only compatible with "standard HNP" MSB or LSB known. We spent some time to add EHNP but is quite complex and we didn't succeed in a short time.

**Comment by heyanheyan** [comment]
ok,thank you very much
