### ISSUE TITLE
minimum number of signatures

### ISSUE THREAD

**Issue by heyanheyan** [bitlogik/lattice-attack#9]
Hello, developer! I want to ask you how to calculate the minimum number of signatures required. Which article did you refer to?

**Comment by uith1hftkb** [comment]
Now l have signatures over 100k from the same key or sender because all correspond to one public key where l have anayslsed that most of the their 2 to 3 r values bytes are fixed or the same but l don't know any ideal about the k nonuce but am l want to guess starting from 0  because l believe keys or nonce start from 0 to f  and with my signatures l believe 0 as the first msb of k must have been used what is my success rate am planning to run all the 100k signatures advice me on what to do Mr developer
